version: "3.7"

services:
  rabbitmq:
    volumes:
      - ./container_fixtures/rabbitmq/certs/ca_certificate.pem:/etc/ssl/certs/ca_certificate.pem
      - ./container_fixtures/rabbitmq/certs/server_rabbit.trento.local_key.pem:/var/lib/rabbitmq/server_rabbit.trento.local_key.pem
      - ./container_fixtures/rabbitmq/certs/server_rabbit.trento.local_certificate.pem:/var/lib/rabbitmq/server_rabbit.trento.local_certificate.pem
      - ./container_fixtures/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    image: rabbitmq:3.12.6-management-alpine
    ports:
      - 5676:5671
      - 5674:5672
      - 15674:15672
    environment:
      RABBITMQ_DEFAULT_USER: wanda
      RABBITMQ_DEFAULT_PASS: wanda
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
